services:
  db:
    image: postgres:16
    container_name: cars-db
    environment:
      POSTGRES_DB: cars
      POSTGRES_USER: cars_user
      POSTGRES_PASSWORD: cars_pass
    ports:
      - "5433:5432"
    volumes:
      - cars_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: cars-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db


volumes:
  cars_pgdata:
